name: build

on: [ push, pull_request ]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libreadline-dev libx11-dev libpng-dev

    - name: Build
      run: make

  build-ubuntu-22_04:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libreadline-dev libx11-dev libpng-dev

    - name: Build
      run: make

  build-ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libreadline-dev libx11-dev libpng-dev

    - name: Build
      run: make

  build-ubuntu-18_04:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libreadline-dev libx11-dev libpng-dev

    - name: Build
      run: make
